# docker build -f Dockerfile-Wx -t ccr.ccs.tencentyun.com/tcb-******-yhmi/ca-ohbsqtpw_go-template-ddd:go-template-ddd-001-20250402185627 ./
FROM golang:1.22-alpine as builder

WORKDIR /app

COPY . /app/

RUN go mod tidy

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./build/go-template-ddd

FROM alpine

WORKDIR /root

COPY --from=builder /app/build/go-template-ddd /root/
COPY --from=builder /app/config/config.toml /root/config/
COPY --from=builder /app/migration /root/migration

CMD ["/root/go-template-ddd", "-c", "/root/config/config.toml"]
