service_name = "go-template-ddd-toml"
port = 8080

mongo_dns = "mongodb://user:password@127.0.0.1:27017/go-template-ddd?authSource=admin"
mysql_dns = "mysql://root:root@127.0.0.1:3306/go-template-ddd?charset=utf8mb4&parseTime=True&loc=Local"

[logger]
    level = "info"
    file = "go-template-ddd.log"
