service_name = "go-template-ddd-toml"
port = 8080

#mongo_dsn = "mongodb://root:root@127.0.0.1:27017/go-template-ddd?authSource=admin"
#mongo_dsn = "mongodb://hezebin:HZB183318a.@mongo-sts-0.mongo.default:27017,mongo-sts-1.mongo.default:27017/blog?authSource=admin"
#mysql_dsn = "mysql://root:root@127.0.0.1:3306/go-template-ddd?charset=utf8mb4&parseTime=True&loc=Local"
#oss_dsn = "minio://CscaPrbfoRO0EapeM56m:RNxYKk9XtdIAyFnCHNLnyYei2tmX4L59ACeDe0Ap@127.0.0.1:9000/test"

[logger]
    level = "info"
    filename = "go-template-ddd.log"

#[redis]
#    addrs = ["127.0.0.1:6379"]
#    password = "root"
#[redis]
#addrs = ["redis-sts-0.redis.default:7000", "redis-sts-1.redis.default:7000", "redis-sts-2.redis.default:7000"]
#password = "HZB183318a."

#[pulsar]
#    url = "pulsar://localhost:6650"
#    topic = "persistent://public/default/go-template-ddd"
#    subscription = "go-template-ddd"

#[kafka]
#    address = "127.0.0.1:9092"
#    topic = "go-template-ddd"
#    partition = 0