service_name = "go-template-ddd"
port = 8080

#mongo_dsn = "mongodb://root:root@127.0.0.1:27017/go-template-ddd?authSource=admin&replicaSet=rs0"
#mongo_dsn = "mongodb://hezebin:root@mongo-sts-0.mongo.default:27017,mongo-sts-1.mongo.default:27017/go-template-ddd?authSource=admin&replicaSet=rs0"
#mysql_dsn = "mysql://root:root@127.0.0.1:3306/go-template-ddd?charset=utf8mb4&parseTime=True&loc=Local"
#oss_dsn = "minio://CscaPrbfoRO0EapeM56m:RNxYKk9XtdIAyFnCHNLnyYei2tmX4L59ACeDe0Ap@127.0.0.1:9000/test"
#elasticsearch_url = "http://localhost:9200"
[logger]
level = "info"
filename = "log/go-template-ddd.log"

[remote]
#user_center_host = "http://localhost:8081"
#[email]
#    host="smtp.qq.com"
#    port=587
#    username="xxx@qq.com"
#    password="xxxxx"
# [sms_tencent]
# secret_id = "SecretId"
# secret_key = "SecretKey"
# region = "ap-guangzhou"
# app_id = "xxx"
# sign_name = "xxx"
# captcha_template_id = "xxxx"
# [sms_aliyun]
# access_key_id = "xxxx"
# access_key_secret = "xxxxx"
# endpoint = ""
# sign_name = "xxx"
# captcha_template_code = "xxxx"
#[redis]
#    addrs = ["127.0.0.1:6379"]
#    password = "root"
#[redis]
#   addrs = ["redis-sts-0.redis.default:7000", "redis-sts-1.redis.default:7000", "redis-sts-2.redis.default:7000"]
#   password = "root"
#[pulsar]
#    url = "pulsar://localhost:6650"
#    topic = "persistent://public/default/go-template-ddd"
#    subscription = "go-template-ddd"
#[kafka]
#    address = "127.0.0.1:9092"
#    topic = "go-template-ddd"
#    partition = 0

# [sms_tencent]
# secret_id = "xxxx"
# secret_key = "xxxxx"
# region = "ap-guangzhou"
# app_id = "xxxx"
# sign_name = "xxx"
# captcha_template_id = "xxx"

# [sms_aliyun]
# access_key_id = "xxx"
# access_key_secret = "xxx"
# sign_name = "xxx"
# captcha_template_code = "xxx"

[wx]
host = "https://api.weixin.qq.com"
app_id = "xxxxxxx"
secret = "xxxxxxxx"
